### ISSUE TITLE
Need help.

### ISSUE THREAD

**Issue by RandumGuy** [Balzabu/Clippy#1]
First of all i want to say great tool , second i have a question.

Could u make a version that will allow me to replace the btc stealer with any other script ?

i tried removing the btc stealer and replacing it with a token grabber and then 

`if __name__ == "__main__":
	setup()
	tokengrabber()`
But that didn't work sadly.

If not , thats no problem. Thanks for the tool !

**Comment by Balzabu** [comment]
Hello, thanks for your comment. Can you explain more what kind of token are you trying to get? 

Anyhow it's possible to edit this to perform said action but I don't think using this source code as a base could be useful, better to rewrite everything.

**Comment by Balzabu** [comment]
Hello, I'm going to close this. If you want to talk further I suggest you to write me an email.

Have a nice time.
